orbs:
  aws-ecr: circleci/aws-ecr@6.9.1
version: 2.1
workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_ENV_VAR_NAME
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
          region: AWS_REGION_ENV_VAR_NAME
          repo: 445496399600.dkr.ecr.eu-central-1.amazonaws.com/rxdb-learn
          tag: "latest,circle-ci"
